---
- name: Set timezone
  win_timezone:
    timezone: "{{ timezone }}"

- name: Set language and reboot if required
  win_region:
    unicode_language: "{{ unicode_language }}"
  register: result
- win_reboot:
  when: result.restart_required
