- name: Configure all web servers
  hosts: webservers
  # serial: 1
  tasks:
    - name: Common role
      include_role:
        name: common
      vars:
        timezone: GMT Standard Time
        unicode_language: en-GB

    - name: Install IIS
      win_feature:
        name: "Web-Server"
        state: present
        restart: no
        include_sub_features: no
        include_management_tools: yes
      register: iisresult

    - name: Reboot if required
      win_reboot:
      when: iisresult.restart_required
      debugger: on_failed
